# my-router settings. Copied to /etc/my-router/settings.conf on first install
# and never overwritten by updates, so per-router edits survive.

# GitHub repo to pull from.
MY_ROUTER_REPO=Dimignat/my-router
MY_ROUTER_BRANCH=master
